# Generated by Django 4.2.7 on 2023-11-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlacuacheApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(),
        ),
    ]
