# Generated by Django 4.2.7 on 2023-11-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlacuacheApp', '0002_alter_post_description_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
