# Generated by Django 4.2.7 on 2023-11-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlacuacheApp', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(),
        ),
    ]
